#!/usr/bin/env python3
import time
import serial
import serial.tools.list_ports as lst
import os

info = lst.comports()

ser = serial.Serial()

logPath = "/home/ubuntu/logs/"

i = 0
while os.path.exists(logPath+"%s.log" % i):
    i += 1

i -= 1

#log = open(logPath+"%s_GPS.log" % i, "w")


def find_Stm():
    for port in info:
        if(port.product.find("u-blox") != -1):
            return port.device
    for port in info:
        if(port.product.find("Pyboard") != -1):
            return port.device
    return 0


def open_device(dev):
    ser.port = dev
    ser.baudrate = 2250000
    ser.open()
    ser.readline()

if __name__ == "__main__":
    if find_Stm() != 0:
        open_device(find_Stm())
    else:
        print("no STM32 Detected, Exit_Program")
        exit(0)

    while True:
        try:
            msg = str(ser.readline(), 'ascii')
            msg = str(time.time()) + "\t" + msg
            print(msg)
            #log.write(msg)
        except KeyboardInterrupt:
            time.sleep(0.001)
            log.close()
            exit(0)

